version: "3"
services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"

  api-server:
    image: api-server
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# networks:
#   mern-app:
#     driver: bridge

volumes:
  mongo-data:
    driver: local
